from .base_model import OCR
from .layout_models.surya_layout import SuryaLayout
from .layout_models.azure_layout import AzureLayout
from .text_extraction_models.surya_text_extraction import SuryaTextExtraction
from .text_extraction_models.azure_text_extraction import AzureTextExtraction
from .text_extraction_models.trocr_text_extraction import TROCRTextExtraction
from .text_extraction_models.tesseract_text_extraction import TesseractTextExtraction
